export const pokemon_settings = [
    [ "overlay_color",          "#000000", ],
    [ "imageXOffset",           0,         ],
    [ "imageYOffset",           0,         ],
    [ "imageScale",             1,         ],
    [ "imageFlip",              false,     ],
    [ "imageSat",               100,       ],
    [ "imageRotation",          0,         ],
    [ "backgroundBlur",         0,         ],
    [ "backgroundScale",        100,       ],
    [ "backgroundFlip",         false,     ],
    [ "backgroundUrl",          '',        ],
    [ "backgroundXOffset",      100,       ],
    [ "backgroundYOffset",      100,       ],
    [ "backgroundTexture",      'Bug 1'    ],
    [ "backgroundBrightness",   100,       ],
    [ "backgroundContrast",     100,       ],
    [ "backgroundSaturation",   100,       ],
    [ "backgroundHue",          0,         ],
    [ "player_id",              0,         ],
    [ "flag_finished_logging_splits",          false,     ],
    [ "blackout",               false,     ],
    [ "faults",                 0,         ],
    [ "split_logStr",           "",        ],
    [ "simple_data_str",        "",        ],
    [ "full_data_str",          "",        ],
    [ "deprecated_data_str",    "",        ],
    [ "simple_data",            "",        ],
    [ "ui_saturation",          0.6,       ],
    [ "previous_label",         "Previous", ],
    [ "current_label",          "Current", ],
    [ "refilming_mode",         false, ],
    [ "refilmed_attempt",       0, ],
    [ "refilmed_finish",        0, ],
];