export type FullSplit = {
	"date_string": any,
	"time_string": any,
	"player_name": any,
	"pokemon": any,
	"trainer_name": any,
	"trainer_id": any,
	"location": any,
	"total_pokemon": any,
	"real_time_total": any,
	"real_time_hmmss": any,
	"real_time_file_label": any,
	"resets": any,
	"blackouts": any,
	"failures": any,
	"level": any,
	"game_time": any,
	"battle_duration": any,
	"move1": any,
	"move2": any,
	"move3": any,
	"move4": any,
	"move1pp": any,
	"move2pp": any,
	"move3pp": any,
	"move4pp": any,
	"move1ppUp": any,
	"move2ppUp": any,
	"move3ppUp": any,
	"move4ppUp": any,
	"saves": any,
	"steps": any,
	"bonks": any,
	"trainerBattles": any,
	"wildBattles": any,
	"battleTurns": any,
	"playerTurns": any,
	"enemyTurns": any,
	"itemsInBag": any,
	"money": any,
	"rivalTeam": any,
	"statusCondition": any,
	"type1": any,
	"type2": any,
	"experience": any,
	"ROM": any,
	"Species": any,
	"Trainer": any,
	"Start Time": any,
	"Real Time": any,
	"Game Time": any,
	"Level": any,
	"Resets": any,
	"RTHours": any,
	"RTMinutes": any,
	"RTSeconds": any,
	"RTMilliseconds": any,
	"Move 1": any,
	"Move 2": any,
	"Move 3": any,
	"Move 4": any,
	"Hp": any,
	"Max HP": any,
	"Attack": any,
	"Defense": any,
	"Sp. Attack": any,
	"Sp. Defense": any,
	"Speed": any,
	"Attack DV": any,
	"Defense DV": any,
	"Speed DV": any,
	"Special DV": any,
	"StatExp HP": any,
	"StatExp Attack": any,
	"StatExp Def": any,
	"StatExp Sp. Attack": any,
	"StatExp Sp. Defense": any,
	"StatExp Speed": any,
	"Attack Stage": any,
	"Defense Stage": any,
	"Sp. Attack Stage": any,
	"Sp. Defense Stage": any,
	"Speed Stage": any,
	"Accuracy Stage": any,
	"Evasion Stage": any,
	"Battle Attack": any,
	"Battle Defense": any,
	"Battle Sp. Attack": any,
	"Battle Sp. Defense": any,
	"Battle Speed": any,
	"Frame Count": any,
	"Overworld Frame Count": any,
	"Battle Frame Count": any,
	"Menu Frame Count": any,
	"Intro Frame Count": any,
	"Save Count": any,
	"Reload Count": any,
	"Clock Reset Count": any,
	"Steps Count": any,
	"Steps Count Walk": any,
	"Steps Count Bike": any,
	"Steps Count Surf": any,
	"Bonks": any,
	"Battles": any,
	"Trainer Battles": any,
	"Wild Battles": any,
	"Battles Fled": any,
	"Failed Runs": any,
	"Total Damage Dealt": any,
	"Actual Damage Dealt": any,
	"Total Damage Taken": any,
	"Actual Damage Taken": any,
	"Own Moves Hit": any,
	"Own Moves Missed": any,
	"Enemy Moves Hit": any,
	"Enemy Moves Missed": any,
	"Own Moves Super Effective": any,
	"Own Moves Not Very Effective": any,
	"Enemy Moves Super Effective": any,
	"Enemy Moves Not Very Effective": any,
	"Criticals Dealt": any,
	"OHKOs Dealt": any,
	"Criticals Taken": any,
	"OHKOs Taken": any,
	"Was Confused": any,
	"Enemy Became Confused": any,
	"Was Paralyzed": any,
	"Enemy Was Paralyzed": any,
	"Was Burned": any,
	"Enemy Was Burned": any,
	"Was Frozen": any,
	"Enemy Was Frozen": any,
	"Was Poisoned": any,
	"Enemy Was Poisoned": any,
	"Was Badly Poisoned": any,
	"Enemy Was Badly Poisoned": any,
	"Fell Asleep": any,
	"Enemy Fell Asleep": any,
	"Player Turns Confused": any,
	"Player Turns Confused Hit Self": any,
	"Player Turns Paralyzed": any,
	"Player Turns Paralyzed Fully": any,
	"Enemy Turns Confused": any,
	"Enemy Turns Confused Hit Self": any,
	"Enemy Turns Paralyzed": any,
	"Enemy Turns Paralyzed Fully": any,
	"Player Turns Asleep": any,
	"Enemy Turns Asleep": any,
	"Player HP Healed": any,
	"Enemy HP Healed": any,
	"Player Pokemon Fainted": any,
	"Enemy Pokemon Fainted": any,
	"Experience Gained": any,
	"Switchouts": any,
	"Money Made": any,
	"Money Spent": any,
	"Money Lost": any,
	"Items Picked Up": any,
	"Items Bought": any,
	"Items Sold": any,
	"Balls Thrown": any,
	"Pokemon Caught In Balls": any,
	"Moves Learnt": any,
	"Blackouts": any,
	"Attempt Number": any,
	"Failures": any,
	"Rival's Team": any,
};


export type SplitHeading = keyof FullSplit;