const pokemon_settings = [
    [ "overlay_color",          "#000000", ],
    [ "imageXOffset",           0,         ],
    [ "imageYOffset",           0,         ],
    [ "imageScale",             1,         ],
    [ "imageFlip",              false,     ],
    [ "imageSat",               100,       ],
    [ "imageRotation",          0,         ],
    [ "backgroundBlur",         0,         ],
    [ "backgroundScale",        100,       ],
    [ "backgroundUrl",          '',        ],
    [ "use_custom_background",  false,     ],
    [ "attempt_number",         0,         ],
    [ "finished_run_count",     0,         ],
    [ "pb_time",                '',        ],
    [ "backgroundXOffset",      100,       ],
    [ "backgroundYOffset",      100,       ],
    [ "backgroundTexture",      'Bug 1'    ],
    [ "backgroundBrightness",   100,       ],
    [ "backgroundContrast",     100,       ],
    [ "backgroundSaturation",   100,       ],
    [ "backgroundHue",          0,         ],
    [ "ui_saturation",          0.6,       ],
    [ "ui_type_colors",         "Bulbapedia Current", ],
    [ "ui_type_color_modifier", "current_",           ],
];