const pokemon_settings = [
    [ "overlay_color",          "#000000", ],
    [ "imageXOffset",           0,         ],
    [ "imageYOffset",           0,         ],
    [ "imageScale",             1,         ],
    [ "imageFlip",              false,     ],
    [ "imageSat",               100,       ],
    [ "imageRotation",          0,         ],
    [ "backgroundBlur",         0,         ],
    [ "backgroundScale",        100,       ],
    [ "backgroundFlip",         false,     ],
    [ "backgroundUrl",          '',        ],
    [ "attempt_number",         0,         ],
    [ "finished_run_count",     0,         ],
    [ "pb_time",                '',        ],
    [ "backgroundXOffset",      100,       ],
    [ "backgroundYOffset",      100,       ],
    [ "backgroundTexture",      'Bug 1'    ],
    [ "backgroundBrightness",   100,       ],
    [ "backgroundContrast",     100,       ],
    [ "backgroundSaturation",   100,       ],
    [ "backgroundHue",          0,         ],
    [ "playerId",               0,         ],
    [ "playerName",             "NINTEN",  ],
    [ "blackout_counter",       0,         ],
    [ "finished_logs",          false,     ],
    [ "attempt_number",         0,         ],
    [ "finished_run_count",     0,         ],
    [ "blackout",               false,     ],
    [ "faults",                 0,         ],
    [ "pb_time",                "None",    ],
    [ "split_logStr",           "",        ],
    [ "simple_data_str",        "",        ],
    [ "full_data_str",          "",        ],
    [ "deprecated_data_str",    "",        ],
    [ "simple_data",            "",        ],
    [ "ui_saturation",          0.6,       ],
    // [ "previous_splits",        [], ],
    // [ "current_splits",         [], ],
    // [ "compared_splits",        [], ],
    [ "previous_label",         "Previous", ],
    [ "current_label",          "Current", ],
    [ "refilming_mode",         false, ],
    [ "refilmed_attempt",       0, ],
    [ "refilmed_finish",        0, ],
    [ "dropdown_bonks_items",   'Bonks', ],
    [ "show_bonk_counter",      true, ],
    [ "toggle_compare_splits",  'First', ],
    [ "show_repel_counter",     true, ],
];