const pokemon_settings = [
    [ "overlay_color",          "#000000", ],
    [ "imageXOffset",           0,         ],
    [ "imageYOffset",           0,         ],
    [ "imageScale",             1,         ],
    [ "imageFlip",              false,     ],
    [ "imageSat",               100,       ],
    [ "imageRotation",          0,         ],
    [ "backgroundBlur",         0,         ],
    [ "backgroundScale",        100,       ],
    [ "backgroundUrl",          '',        ],
    [ "use_custom_background",  false,     ],
    [ "attempt_number",         0,         ],
    [ "finished_run_count",     0,         ],
    [ "pb_time",                '',        ],
    [ "backgroundXOffset",      100,       ],
    [ "backgroundYOffset",      100,       ],
    [ "backgroundTexture",      'Bug 1'    ],
    [ "backgroundBrightness",   100,       ],
    [ "backgroundContrast",     100,       ],
    [ "backgroundSaturation",   100,       ],
    [ "backgroundHue",          0,         ],
    [ "playerId",               0,         ],
    [ "playerName",             "NINTEN",  ],
    [ "resetCatcher",           "NINTEN",  ],
    [ "playerResets",           0,         ],
    [ "blackout_counter",       0,         ],
    [ "resetCounter",           true,      ],
    [ "game_over",              false,     ],
    [ "lance_defeated",         false,     ],
    [ "finished_logs",          false,     ],
    [ "attempt_number",         0,         ],
    [ "finished_run_count",     0,         ],
    [ "blackouts_as_resets",    false,     ], //counts blackouts as resets
    [ "blackout",               false,     ],
    [ "faults",                 0,         ],
    [ "pb_time",                "None",    ],
    [ "most_recent_move",       "",        ],
    [ "split_logStr",           "",        ],
    [ "simple_data_str",        "",        ],
    [ "full_data_str",          "",        ],
    [ "deprecated_data_str",    "",        ],
    [ "simple_data",            "",        ],
    [ "ui_saturation",          0.6,       ],
    [ "ui_type_colors",         "Bulbapedia Current", ],
    [ "ui_type_color_modifier", "current_",           ],
    // [ "previous_splits",        [], ],
    // [ "current_splits",         [], ],
    // [ "compared_splits",        [], ],
    [ "previous_label",         "Previous", ],
    [ "current_label",          "Current", ],
    [ "refilming_mode",         false, ],
    [ "refilmed_attempt",       0, ],
    [ "refilmed_finish",        0, ],
    
];