import { BattleSummaryConfig } from "../types";

export const gen1_battle_summary: BattleSummaryConfig = {
    global_stats: [
        { data_name: "battle_summary_frames",        name: "Battle Frames",     path: "patch.time.battleFrameCount.value",                       },
        { data_name: "battle_summary_battle_number", name: "Battle Number",     path: "patch.battles.trainerBattles.value",                      },
        { data_name: "battle_summary_exp_gained",    name: "Experience Gained", path: "patch.battle_info.experienceGained.value",                },
        { data_name: "battle_summary_turns",         name: "Battle Turns",      path: "patch.battle_info.turns.battleTurns.value",               },
        { data_name: "battle_summary_player_turns",  name: "Player Turns",      path: "patch.battle_info.turns.playerTurns.value",               },
        { data_name: "battle_summary_player_hits",   name: "Hits",              path: "patch.battle_info.hits.ownMovesHit.value",                },
        { data_name: "battle_summary_player_misses", name: "Misses",            path: "patch.battle_info.hits.ownMovesMissed.value",             },
        { data_name: "battle_summary_player_crits",  name: "Crits",             path: "patch.battle_info.hits.criticalsDealt.value",             },
        { data_name: "battle_summary_player_ohkos",  name: "OHKOs",             path: "patch.battle_info.hits.oHKOsDealt.value",                 },
        { data_name: "battle_summary_enemy_turns",   name: "Enemy Turns",       path: "patch.battle_info.turns.enemyTurns.value",                },
        { data_name: "battle_summary_enemy_hits",    name: "Hits",              path: "patch.battle_info.hits.enemyMovesHit.value",              },
        { data_name: "battle_summary_enemy_misses",  name: "Misses",            path: "patch.battle_info.hits.enemyMovesMissed.value",           },
        { data_name: "battle_summary_enemy_crits",   name: "Crits",             path: "patch.battle_info.hits.criticalsTaken.value",             },
        { data_name: "battle_summary_enemy_ohkos",   name: "OHKOs",             path: "patch.battle_info.hits.oHKOsTaken.value",                 },
        { data_name: "battle_summary_player_Sx",     name: "Status Moves",      path: "patch.battle_info.turns.hits.PlayerMovesStatus.value",    },
        { data_name: "battle_summary_player_4x",     name: "4x Damage Moves",   path: "patch.battle_info.turns.hits.PlayerMoves4xE.value",       },
        { data_name: "battle_summary_player_2x",     name: "2x Damage Moves",   path: "patch.battle_info.turns.hits.PlayerMoves2xE.value",       },
        { data_name: "battle_summary_player_1x",     name: "Neutral Moves",     path: "patch.battle_info.turns.hits.PlayerMoves1xE.value",       },
        { data_name: "battle_summary_player_Hx",     name: "1/2x Damage Moves", path: "patch.battle_info.turns.hits.PlayerMoves2xR.value",       },
        { data_name: "battle_summary_player_Qx",     name: "1/4x Damage Moves", path: "patch.battle_info.turns.hits.PlayerMoves4xR.value",       },
        { data_name: "battle_summary_player_0x",     name: "No Effect Moves",   path: "patch.battle_info.turns.hits.PlayerMoves0xE.value",       },
        { data_name: "battle_summary_player_con",    name: "Confused",          path: "patch.battle_info.turns.hits.wasConfused.value",          },
        { data_name: "battle_summary_player_par",    name: "Paralyzed",         path: "patch.battle_info.turns.hits.wasParalyzed.value",         },
        { data_name: "battle_summary_player_brn",    name: "Burned",            path: "patch.battle_info.turns.hits.wasBurned.value",            },
        { data_name: "battle_summary_player_frz",    name: "Frozen",            path: "patch.battle_info.turns.hits.wasFrozen.value",            },
        { data_name: "battle_summary_player_psn",    name: "Poisoned",          path: "patch.battle_info.turns.hits.wasPoisoned.value",          },
        { data_name: "battle_summary_player_bpn",    name: "Badly Poison",      path: "patch.battle_info.turns.hits.wasPoisonedBadly.value",     },
        { data_name: "battle_summary_player_slp",    name: "Fell Asleep",       path: "patch.battle_info.turns.hits.fellAsleep.value",           },
        { data_name: "battle_summary_enemy_Sx",      name: "Status Moves",      path: "patch.battle_info.turns.hits.EnemyMovesStatus.value",     },
        { data_name: "battle_summary_enemy_4x",      name: "4x Damage Moves",   path: "patch.battle_info.turns.hits.EnemyMoves4xE.value",        },
        { data_name: "battle_summary_enemy_2x",      name: "2x Damage Moves",   path: "patch.battle_info.turns.hits.EnemyMoves2xE.value",        },
        { data_name: "battle_summary_enemy_1x",      name: "Neutral Moves",     path: "patch.battle_info.turns.hits.EnemyMoves1xE.value",        },
        { data_name: "battle_summary_enemy_Hx",      name: "1/2x Damage Moves", path: "patch.battle_info.turns.hits.EnemyMoves2xR.value",        },
        { data_name: "battle_summary_enemy_Qx",      name: "1/4x Damage Moves", path: "patch.battle_info.turns.hits.EnemyMoves4xR.value",        },
        { data_name: "battle_summary_enemy_0x",      name: "No Effect Moves",   path: "patch.battle_info.turns.hits.EnemyMoves0xE.value",        },
        { data_name: "battle_summary_enemy_con",     name: "Confused",          path: "patch.battle_info.turns.hits.enemyBecameConfused.value",  },
        { data_name: "battle_summary_enemy_par",     name: "Paralyzed",         path: "patch.battle_info.turns.hits.enemyWasParalyzed.value",    },
        { data_name: "battle_summary_enemy_brn",     name: "Burned",            path: "patch.battle_info.turns.hits.enemyWasBurned.value",       },
        { data_name: "battle_summary_enemy_frz",     name: "Frozen",            path: "patch.battle_info.turns.hits.enemyWasFrozen.value",       },
        { data_name: "battle_summary_enemy_psn",     name: "Poisoned",          path: "patch.battle_info.turns.hits.enemyWasPoisoned.value",     },
        { data_name: "battle_summary_enemy_bpn",     name: "Badly Poison",      path: "patch.battle_info.turns.hits.enemyWasPoisonedBadly.value",},
        { data_name: "battle_summary_enemy_slp",     name: "Fell Asleep",       path: "patch.battle_info.turns.hits.enemyFellAsleep.value",      },
    ],
    global: [
        { data_name: "battle_summary_frames",        name: "Battle Frames",     path: "patch.time.battleFrameCount.value",         },
        { data_name: "battle_summary_turns",         name: "Battle Turns",      path: "patch.battle_info.turns.battleTurns.value", },
        { data_name: "battle_summary_exp_gained",    name: "Experience Gained", path: "patch.battle_info.experienceGained.value",  },
        { data_name: "battle_summary_battle_number", name: "Battle Number",     path: "patch.battles.trainerBattles.value",        },
    ],
    player: [
        { data_name: "battle_summary_player_turns",  name: "Turns",  path: "patch.battle_info.turns.playerTurns.value",   },
        { data_name: "battle_summary_player_hits",   name: "Hits",   path: "patch.battle_info.hits.ownMovesHit.value",    },
        // { data_name: "battle_summary_player_misses", name: "Misses", path: "patch.battle_info.hits.ownMovesMissed.value", },
        { data_name: "battle_summary_player_crits",  name: "Crits",  path: "patch.battle_info.hits.criticalsDealt.value", },
        // { data_name: "battle_summary_player_ohkos",  name: "OHKOs",  path: "patch.battle_info.hits.oHKOsDealt.value",     },
    ],
    enemy: [
        { data_name: "battle_summary_enemy_turns",  name: "Turns",  path: "patch.battle_info.turns.enemyTurns.value",   },
        { data_name: "battle_summary_enemy_hits",   name: "Hits",   path: "patch.battle_info.hits.enemyMovesHit.value", },
        // { data_name: "battle_summary_enemy_misses", name: "Misses", path: "patch.battle_info.hits.enemyMovesMissed.value", },
        { data_name: "battle_summary_enemy_crits",  name: "Crits",  path: "patch.battle_info.hits.criticalsTaken.value", },
        // { data_name: "battle_summary_enemy_ohkos",  name: "OHKOs",  path: "patch.battle_info.hits.oHKOsTaken.value",  },
    ],
} as const