const battle_summary = {
    global_stats: [
        { data_name: "battle_summary_frames",        name: "Battle Frames",     path: "patch.time.battleFrameCount.value",                        type: "number",},
        { data_name: "battle_summary_battle_number", name: "Battle Number",     path: "patch.battles.trainerBattles.value",                       type: "number",},
        { data_name: "battle_summary_exp_gained",    name: "Experience Gained", path: "patch.battle_info.experienceGained.value",                 type: "number",},
        { data_name: "battle_summary_turns",         name: "Battle Turns",      path: "patch.battle_info.turns.battleTurns.value",                type: "number",},
        { data_name: "battle_summary_player_turns",  name: "Player Turns",      path: "patch.battle_info.turns.playerTurns.value",                type: "number",},
        { data_name: "battle_summary_player_hits",   name: "Hits",              path: "patch.battle_info.hits.ownMovesHit.value",                 type: "number",},
        { data_name: "battle_summary_player_misses", name: "Misses",            path: "patch.battle_info.hits.ownMovesMissed.value",              type: "number",},
        { data_name: "battle_summary_player_crits",  name: "Crits",             path: "patch.battle_info.hits.criticalsDealt.value",              type: "number",},
        { data_name: "battle_summary_player_ohkos",  name: "OHKOs",             path: "patch.battle_info.hits.oHKOsDealt.value",                  type: "number",},
        { data_name: "battle_summary_enemy_turns",   name: "Enemy Turns",       path: "patch.battle_info.turns.enemyTurns.value",                 type: "number",},
        { data_name: "battle_summary_enemy_hits",    name: "Hits",              path: "patch.battle_info.hits.enemyMovesHit.value",               type: "number",},
        { data_name: "battle_summary_enemy_misses",  name: "Misses",            path: "patch.battle_info.hits.enemyMovesMissed.value",            type: "number",},
        { data_name: "battle_summary_enemy_crits",   name: "Crits",             path: "patch.battle_info.hits.criticalsTaken.value",              type: "number",},
        { data_name: "battle_summary_enemy_ohkos",   name: "OHKOs",             path: "patch.battle_info.hits.oHKOsTaken.value",                  type: "number",},
        { data_name: "battle_summary_player_Sx",     name: "Status Moves",      path: "patch.battle_info.turns.hits.PlayerMovesStatus.value",     type: "number",},
        { data_name: "battle_summary_player_4x",     name: "4x Damage Moves",   path: "patch.battle_info.turns.hits.PlayerMoves4xE.value",        type: "number",},
        { data_name: "battle_summary_player_2x",     name: "2x Damage Moves",   path: "patch.battle_info.turns.hits.PlayerMoves2xE.value",        type: "number",},
        { data_name: "battle_summary_player_1x",     name: "Neutral Moves",     path: "patch.battle_info.turns.hits.PlayerMoves1xE.value",        type: "number",},
        { data_name: "battle_summary_player_Hx",     name: "1/2x Damage Moves", path: "patch.battle_info.turns.hits.PlayerMoves2xR.value",        type: "number",},
        { data_name: "battle_summary_player_Qx",     name: "1/4x Damage Moves", path: "patch.battle_info.turns.hits.PlayerMoves4xR.value",        type: "number",},
        { data_name: "battle_summary_player_0x",     name: "No Effect Moves",   path: "patch.battle_info.turns.hits.PlayerMoves0xE.value",        type: "number",},
        { data_name: "battle_summary_player_con",    name: "Confused",          path: "patch.battle_info.turns.hits.wasConfused.value",           type: "number",},
        { data_name: "battle_summary_player_par",    name: "Paralyzed",         path: "patch.battle_info.turns.hits.wasParalyzed.value",          type: "number",},
        { data_name: "battle_summary_player_brn",    name: "Burned",            path: "patch.battle_info.turns.hits.wasBurned.value",             type: "number",},
        { data_name: "battle_summary_player_frz",    name: "Frozen",            path: "patch.battle_info.turns.hits.wasFrozen.value",             type: "number",},
        { data_name: "battle_summary_player_psn",    name: "Poisoned",          path: "patch.battle_info.turns.hits.wasPoisoned.value",           type: "number",},
        { data_name: "battle_summary_player_bpn",    name: "Badly Poison",      path: "patch.battle_info.turns.hits.wasPoisonedBadly.value",      type: "number",},
        { data_name: "battle_summary_player_slp",    name: "Fell Asleep",       path: "patch.battle_info.turns.hits.fellAsleep.value",            type: "number",},
        { data_name: "battle_summary_enemy_Sx",      name: "Status Moves",      path: "patch.battle_info.turns.hits.EnemyMovesStatus.value",      type: "number",},
        { data_name: "battle_summary_enemy_4x",      name: "4x Damage Moves",   path: "patch.battle_info.turns.hits.EnemyMoves4xE.value",         type: "number",},
        { data_name: "battle_summary_enemy_2x",      name: "2x Damage Moves",   path: "patch.battle_info.turns.hits.EnemyMoves2xE.value",         type: "number",},
        { data_name: "battle_summary_enemy_1x",      name: "Neutral Moves",     path: "patch.battle_info.turns.hits.EnemyMoves1xE.value",         type: "number",},
        { data_name: "battle_summary_enemy_Hx",      name: "1/2x Damage Moves", path: "patch.battle_info.turns.hits.EnemyMoves2xR.value",         type: "number",},
        { data_name: "battle_summary_enemy_Qx",      name: "1/4x Damage Moves", path: "patch.battle_info.turns.hits.EnemyMoves4xR.value",         type: "number",},
        { data_name: "battle_summary_enemy_0x",      name: "No Effect Moves",   path: "patch.battle_info.turns.hits.EnemyMoves0xE.value",         type: "number",},
        { data_name: "battle_summary_enemy_con",     name: "Confused",          path: "patch.battle_info.turns.hits.enemyBecameConfused.value",   type: "number",},
        { data_name: "battle_summary_enemy_par",     name: "Paralyzed",         path: "patch.battle_info.turns.hits.enemyWasParalyzed.value",     type: "number",},
        { data_name: "battle_summary_enemy_brn",     name: "Burned",            path: "patch.battle_info.turns.hits.enemyWasBurned.value",        type: "number",},
        { data_name: "battle_summary_enemy_frz",     name: "Frozen",            path: "patch.battle_info.turns.hits.enemyWasFrozen.value",        type: "number",},
        { data_name: "battle_summary_enemy_psn",     name: "Poisoned",          path: "patch.battle_info.turns.hits.enemyWasPoisoned.value",      type: "number",},
        { data_name: "battle_summary_enemy_bpn",     name: "Badly Poison",      path: "patch.battle_info.turns.hits.enemyWasPoisonedBadly.value", type: "number",},
        { data_name: "battle_summary_enemy_slp",     name: "Fell Asleep",       path: "patch.battle_info.turns.hits.enemyFellAsleep.value",       type: "number",},
    ],
    saved_settings: [
        "battle_summary_frames",
        "battle_summary_battle_number",
        "battle_summary_exp_gained",
        "battle_summary_turns",
        "battle_summary_player_turns",
        "battle_summary_enemy_turns",
        "battle_summary_player_hits",
        "battle_summary_player_misses",
        "battle_summary_player_crits",
        "battle_summary_player_ohkos",
        "battle_summary_enemy_hits",
        "battle_summary_enemy_misses",
        "battle_summary_enemy_crits",
        "battle_summary_enemy_ohkos",
        "battle_summary_player_Sx",
        "battle_summary_player_4x",
        "battle_summary_player_2x",
        "battle_summary_player_1x",
        "battle_summary_player_Hx",
        "battle_summary_player_Qx",
        "battle_summary_player_0x",
        "battle_summary_player_con",
        "battle_summary_player_par",
        "battle_summary_player_brn",
        "battle_summary_player_frz",
        "battle_summary_player_psn",
        "battle_summary_player_bpn",
        "battle_summary_player_slp",
        "battle_summary_enemy_Sx",
        "battle_summary_enemy_4x",
        "battle_summary_enemy_2x",
        "battle_summary_enemy_1x",
        "battle_summary_enemy_Hx",
        "battle_summary_enemy_Qx",
        "battle_summary_enemy_0x",
        "battle_summary_enemy_con",
        "battle_summary_enemy_par",
        "battle_summary_enemy_brn",
        "battle_summary_enemy_frz",
        "battle_summary_enemy_psn",
        "battle_summary_enemy_bpn",
        "battle_summary_enemy_slp",
    ],
    global: [
        { data_name: "battle_summary_frames",        name: "Battle Frames",     path: "patch.time.battleFrameCount.value",         type: "number",},
        { data_name: "battle_summary_turns",         name: "Battle Turns",      path: "patch.battle_info.turns.battleTurns.value", type: "number",},
        { data_name: "battle_summary_exp_gained",    name: "Experience Gained", path: "patch.battle_info.experienceGained.value",  type: "number",},
        { data_name: "battle_summary_battle_number", name: "Battle Number",     path: "patch.battles.trainerBattles.value",        type: "number",},
    ],
    player: [
        { data_name: "battle_summary_player_turns",  name: "Turns",  path: "patch.battle_info.turns.playerTurns.value",   type: "number",},
        { data_name: "battle_summary_player_hits",   name: "Hits",   path: "patch.battle_info.hits.ownMovesHit.value",    type: "number",},
        // { data_name: "battle_summary_player_misses", name: "Misses", path: "patch.battle_info.hits.ownMovesMissed.value", type: "number",},
        { data_name: "battle_summary_player_crits",  name: "Crits",  path: "patch.battle_info.hits.criticalsDealt.value", type: "number",},
        // { data_name: "battle_summary_player_ohkos",  name: "OHKOs",  path: "patch.battle_info.hits.oHKOsDealt.value",     type: "number",},
    ],
    enemy: [
        { data_name: "battle_summary_enemy_turns",  name: "Turns",  path: "patch.battle_info.turns.enemyTurns.value",      type: "number",},
        { data_name: "battle_summary_enemy_hits",   name: "Hits",   path: "patch.battle_info.hits.enemyMovesHit.value",    type: "number",},
        // { data_name: "battle_summary_enemy_misses", name: "Misses", path: "patch.battle_info.hits.enemyMovesMissed.value", type: "number",},
        { data_name: "battle_summary_enemy_crits",  name: "Crits",  path: "patch.battle_info.hits.criticalsTaken.value",   type: "number",},
        // { data_name: "battle_summary_enemy_ohkos",  name: "OHKOs",  path: "patch.battle_info.hits.oHKOsTaken.value",       type: "number",},
    ],
}