const split_trainers = {
    "Yellow": [
        // "Rival1-Lab",           
        // "Rival1a-Route 22",     
        "Brock",                
        // "Rival2-Nugget Bridge", 
        // "Rival3-SS Anne",       
        "Misty",                
        "Erika",                
        "Surge",                
        "Rival4-Pkmn Tower",    
        "Koga",                 
        "Rival5-Silph",         
        "Sabrina",              
        "Blaine",               
        "Giovanni",             
        // "Rival6-Route 22",      
        "Lorelei",              
        "Bruno",                
        "Agatha",               
        "Lance",                
        "Champion",             
    ],
    "Red and Blue": [
        "Rival1-Lab",           
        "Brock",                
        "Rival2-Nugget Bridge", 
        "Rival3-SS Anne",       
        "Misty",                
        "Erika",                
        "Surge",                
        "Rival4-Pkmn Tower",    
        "Koga",                 
        "Rival5-Silph",         
        "Sabrina",              
        "Blaine",               
        "Giovanni",             
        "Rival6-Route 22",      
        "Lorelei",              
        "Bruno",                
        "Agatha",               
        "Lance",                
        "Champion",             
    ],
}