const trainer_name_lookup = {
    "basic": {
        "Rival1-Lab":           {trainer: "Rival 1",  color: "background-color: #FF0000;",},
        "Rival1a-Route 22":     {trainer: "Rival 1a", color: "background-color: #FF0000;",},
        "Bug Catcher_1":        {trainer: "Bug Catcher_1",    color: "background-color: #FF0000;",},
        "Brock":                {trainer: "Brock",    color: "background-color: #FF0000;",},
        "Brock":                {trainer: "Brock",    color: "background-color: #FF0000;",},
        "Brock":                {trainer: "Brock",    color: "background-color: #FF0000;",},
        "Brock":                {trainer: "Brock",    color: "background-color: #FF0000;",},
        "Brock":                {trainer: "Brock",    color: "background-color: #FF0000;",},
        "Brock":                {trainer: "Brock",    color: "background-color: #FF0000;",},
        "Brock":                {trainer: "Brock",    color: "background-color: #FF0000;",},
        "Rival2-Nugget Bridge": {trainer: "Rival 2",  color: "background-color: #FF0000;",},
        "Cerulean Rocket":      {trainer: "Rocket",   color: "background-color: #FF0000;",},
        "Rival3-SS Anne":       {trainer: "Rival 3",  color: "background-color: #FF0000;",},
        "Misty":                {trainer: "Misty",    color: "background-color: #FF0000;",},
        "Erika":                {trainer: "Erika",    color: "background-color: #FF0000;",},
        "Surge":                {trainer: "Surge",    color: "background-color: #FF0000;",},
        "Rival4-Pkmn Tower":    {trainer: "Rival 4",  color: "background-color: #FF0000;",},
        "Koga":                 {trainer: "Koga",     color: "background-color: #FF0000;",},
        "Rival5-Silph":         {trainer: "Rival 5",  color: "background-color: #FF0000;",},
        "Sabrina":              {trainer: "Sabrina",  color: "background-color: #FF0000;",},
        "Blaine":               {trainer: "Blaine",   color: "background-color: #FF0000;",},
        "Giovanni":             {trainer: "Giovanni", color: "background-color: #FF0000;",},
        "Rival6-Route 22":      {trainer: "Rival 6",  color: "background-color: #FF0000;",},
        "Lorelei":              {trainer: "Lorelei",  color: "background-color: #FF0000;",},
        "Bruno":                {trainer: "Bruno",    color: "background-color: #FF0000;",},
        "Agatha":               {trainer: "Agatha",   color: "background-color: #FF0000;",},
        "Lance":                {trainer: "Lance",    color: "background-color: #FF0000;",},
        "Champion":             {trainer: "Champion", color: "background-color: #FF0000;",},
    },
    "detailed": {
        "Rival1-Lab":           {trainer: "Rival 1 - Lab",  color: "background-color: #FF0000;",},
        "Rival1a-Route 22":     {trainer: "Rival 1a", color: "background-color: #FF0000;",},
        "Brock":                {trainer: "Brock",    color: "background-color: #FF0000;",},
        "Rival2-Nugget Bridge": {trainer: "Rival 2 - Bridge",  color: "background-color: #FF0000;",},
        "Cerulean Rocket":      {trainer: "Rocket",   color: "background-color: #FF0000;",},
        "Rival3-SS Anne":       {trainer: "Rival 3 - SS. Anne",  color: "background-color: #FF0000;",},
        "Misty":                {trainer: "Misty",    color: "background-color: #FF0000;",},
        "Erika":                {trainer: "Erika",    color: "background-color: #FF0000;",},
        "Surge":                {trainer: "Surge",    color: "background-color: #FF0000;",},
        "Rival4-Pkmn Tower":    {trainer: "Rival 4 - Tower",  color: "background-color: #FF0000;",},
        "Koga":                 {trainer: "Koga",     color: "background-color: #FF0000;",},
        "Rival5-Silph":         {trainer: "Rival 5 - Silph",  color: "background-color: #FF0000;",},
        "Sabrina":              {trainer: "Sabrina",  color: "background-color: #FF0000;",},
        "Blaine":               {trainer: "Blaine",   color: "background-color: #FF0000;",},
        "Giovanni":             {trainer: "Giovanni", color: "background-color: #FF0000;",},
        "Rival6-Route 22":      {trainer: "Rival 6 - Route 22",  color: "background-color: #FF0000;",},
        "Lorelei":              {trainer: "Lorelei",  color: "background-color: #FF0000;",},
        "Bruno":                {trainer: "Bruno",    color: "background-color: #FF0000;",},
        "Agatha":               {trainer: "Agatha",   color: "background-color: #FF0000;",},
        "Lance":                {trainer: "Lance",    color: "background-color: #FF0000;",},
        "Champion":             {trainer: "Champion", color: "background-color: #FF0000;",},
    }
}